export const initialState = {
  place: "",
  basicInfo: {},
  attractions: [],
  filteredAttractions: [],
  infoType: "",
  limit: 3,
  map: {},
  filter: "interesting_places",
  weather: {
    apparentTemperature: 0,
    cloudCover: 0,
    dewPoint: 0,
    humidity: 0,
    icon: "",
    lat: 0,
    lng: 0,
    ozone: 0,
    precipIntensity: 0,
    pressure: 0,
    summary: "",
    temperature: 0,
    time: 0,
    uvIndex: 0,
    visibility: 0,
    windBearing: 0,
    windGust: 0,
    windSpeed: 0,
  },
};